


# @name lesson
POST http://localhost:8081/lesson/create
Content-Type: application/json 

{
    "title" : "Garbage Deleted Lesson",
    "instructions": "Ignore this lesson",
    "default_script": "break",
    "solution_verification": "break",
    "is_test": false,
    "chapter_no": 5,
    "order_within_chapter": 7,
    "documentation_id": "2Bdeleted"
}

###
@lessonId = {{lesson.response.body.$._id}}

###
# @name User
POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "User2Delete",
    "email" : "gonna@delete.com",
    "password" : "GetD31373D"
}

###
@userId = {{User.response.body.$._id}}


# @name create
POST http://localhost:8081/submissions/create
Content-Type: application/json 

{
    "userID" : "6a18823fe3a22d37ce5b6b83",
    "lessonID": "6a19e16bd4abefc266f8ab0c"
}

###
@submissionTestId1 = {{create.response.body.$._id}}
@submissionTestUserID1 = {{create.response.body.$.userID}}
@submissionTestLessonID1 = {{create.response.body.$.lessonID}}
@submissionTestScriptSubmission1 = {{create.response.body.$.script_submission}}
###

###



###
GET http://localhost:8081/submissions/getAll
Content-Type: application/json

###

POST http://localhost:8081/submissions/6a25bef72b7fca3270e70900/update
Content-Type: application/json 

{
    "_id": "6a25bef72b7fca3270e70900",
    "userID": "6a18823fe3a22d37ce5b6b83",
    "lessonID": "6a19e16bd4abefc266f8ab0c",
    "script_submission": "Success! # This is the code editor, it allows for the modification of code and programming in general.",
    "success": false,
    "start_date": "2026-06-07T18:57:55.031Z",
    "submission_date": "2026-06-07T20:13:21.578Z",
    "__v": 0}

###
//http://localhost:8081/submissions/6a25bef72b7fca3270e70900/update
###

GET http://localhost:8081/submissions/findSubmission
Content-Type: application/json 

{
    "userID" : "6a18823fe3a22d37ce5b6b83",
    "lessonID": "6a19e16bd4abefc266f8ab0c"
}


###
GET  http://localhost:8081/submissions/load/{{submissionTestId1}}
Content-Type: application/json 

###
POST  http://localhost:8081/submissions/{{submissionTestId1}}/delete
Content-Type: application/json 

###
POST  http://localhost:8081/user/{{userId}}/delete
Content-Type: application/json 

###

POST  http://localhost:8081/lesson/{{lessonId}}/delete
Content-Type: application/json 

###