


# @name lesson
POST http://localhost:8081/lesson/create
Content-Type: application/json 

{
    "title" : "What is a function?",
    "instructions": "Now that we have a good understanding of storing data, let's put it to use. \nLet's start by learning how to use a pre-defined function.\nThis requires importing from a file we'll call Helper. Try importing \"Odd or Even\" from Helper.\n.",
    "default_script": "#To import functions you have to use import statements, followed by the name of the function you're importing.\n# Formatting: import {function_name} from {namespace}",
    "solution_verification": "import oddOrEven from Helper\noddOrEven()",
    "is_test": false,
    "chapter_no": 2,
    "order_within_chapter": 1,
    "documentation_id": "2beMadeLater",
    "description": "A lesson that gives examples of pre-existing functions and how to use them"
}

###
@lessonId = {{lesson.response.body.$._id}}
# @name lesson2
POST http://localhost:8081/lesson/create
Content-Type: application/json 

{
    "title" : "My own function",
    "instructions": "After learning how to import functions, why don't we try making one of our own.\nBegin by typing def functionZero():.\nAfter this, try making a function that runs through 5 loops and returns a value stating how many times it looped by using a \"return\" statement.",
    "default_script": "# Delete me to start coding",
    "solution_verification": "def functionZero():\np=0\t\n\tfor i in range(5):\n\t\tp+=1\n\treturn p",
    "is_test": false,
    "chapter_no": 2,
    "order_within_chapter": 2,
    "documentation_id": "gonnaAddL8r"
}

###
@lessonId2 = {{lesson2.response.body.$._id}}

# @name lesson3
POST http://localhost:8081/lesson/create
Content-Type: application/json 

{
    "title" : "def(Parameter=s):",
    "instructions": "Now that we know how to create our own function, we can learn how to pass parameters into them so they can be more versatile.\nBegin by defining a function that loops a certain amount of times and returns how many loops it went through. \nOnce you have done that, instead of making the range a static value, make it a variable, for example 'h', and put the same value in the parentheses next to the function name.",
    "default_script": "# Remember that you have to put h both in the parentheses for range and the definition of the function.",
    "solution_verification": "def functionZero(h):\np=0\t\n\tfor i in range(h):\n\t\tp+=1\n\treturn p",
    "is_test": true,
    "chapter_no": 2,
    "order_within_chapter": 3,
    "documentation_id": "Nope"
}

###
@lessonId3 = {{lesson3.response.body.$._id}}


# @name create
POST http://localhost:8081/chapter/create
Content-Type: application/json 

{
    "title": "Python Functionality",
    "chapter_no": 2, 
    "description": "In this section you will learn about functions, how to use built-in functions, how to make your own functions, why functions are helpful, and how to use the functions you create.", 
    "documentation_references": "TBD"
}

###
@chapterTestId1 = {{create.response.body.$._id}}
@chapterTestTitle1 = {{create.response.body.$.title}}
@chapterTestDescription = {{create.response.body.$.description}}
@chapterTestTestID = {{create.response.body.$.test_id}}
@chapterTestDocRef = {{create.response.body.$.documentation_references}}
###

###



###
GET http://localhost:8081/chapter/list
Content-Type: application/json

###

POST http://localhost:8081/chapter/{{chapterTestId1}}/edit
Content-Type: application/json 

{
    "title": "Chapter 5: The New and Improved Chapter marked for Deletion",
    "chapter_no": 5, 
    "description": "After being modified this chapter now has lessons assigned to it!", 
    "documentation_references": "Who cares rn."
}
###

POST http://localhost:8081/chapter/{{chapterTestId1}}/refresh
Content-Type: application/json 



###
POST http://localhost:8081/lesson/6a1dbeccb7829fed4e8a331f/edit
Content-Type: application/json 

{
    "is_test" : true,
    "chapter_no": 6
}

###

GET http://localhost:8081/chapter/findChapter
Content-Type: application/json 

{
    "title": null,
    "chapter_no": 2,
    "description": null,
    "test_id": null
}


###
GET  http://localhost:8081/chapter/{{chapterTestId1}}
Content-Type: application/json 

###
POST  http://localhost:8081/chapter/{{chapterTestId1}}/delete
Content-Type: application/json 

###

POST  http://localhost:8081/lesson/{{lessonId}}/delete
Content-Type: application/json 

###
POST  http://localhost:8081/lesson/{{lessonId2}}/delete
Content-Type: application/json 

###
POST  http://localhost:8081/lesson/{{lessonId3}}/delete
Content-Type: application/json 

###