
# @name create
POST http://localhost:8081/lesson/create
Content-Type: application/json 

{
    "title" : "Experimental Rework of Solution Verification",
    "instructions": "Please do ignore this, as you are not meant to see it.",
    "default_script": "# This is the code editor, it allows for the modification of code and programming in general.\n",
    "solution_verification": {
        "funcName": "functionZero",
        "testCases": [
            { "args": [5], "expected": 5 },
            { "args": [201], "expected": 201 },
            { "args": [74], "expected": 74 }
            ]
        },
    "is_test": false,
    "chapter_no": 0,
    "order_within_chapter": 1,
    "documentation_id": "To be fixed later"
}

###
@lessonTestId1 = {{create.response.body.$._id}}
@lessonTestTitle1 = {{create.response.body.$.title}}
@lessonTestInstruction1 = {{create.response.body.$.instructions}}
@lessonTestDefaultScript1 = {{create.response.body.$.default_script}}
@lessonTestSolutionVerification1 = {{create.response.body.$.solution_verification}}
@lessonTestIsTest1 = {{create.response.body.$.is_test}}
@lessonTestChapterNo1 = {{create.response.body.$.chapter_no}}
@lessonTestChapterOrder1 = {{create.response.body.$.order_within_chapter}}
@lessonTestDocumentId1 = {{create.response.body.$.documentation_id}}

###

POST http://localhost:8081/lesson/load
Content-Type: application/json 

{
    "lessonId" : "{{lessonTestId1}}"
}


###
GET http://localhost:8081/lesson/getAll
Content-Type: application/json

###

POST http://localhost:8081/lesson/{{lessonTestId1}}/edit
Content-Type: application/json 

{
    "title" : "Title Replaced",
    "instructions" : "Instructions Modified",
    "default_script" : "Script Rewritten",
    "solution_verification" : "Solution Corrected",
    "is_test" : true,
    "documentation_id" : "Document #57221"
}

###

GET http://localhost:8081/lesson/findLesson
Content-Type: application/json 

{
"title": null,
"instructions": null,
"default_script": null,
"solution_verification": null,
"is_test": null,
"chapter_no": 2,
"order_within_chapter": null,
"documentation_id": null
}


###
GET  http://localhost:8081/lesson/6a27093019793c4ac9a07a56
Content-Type: application/json 

###
POST  http://localhost:8081/lesson/{{lessonTestId1}}/delete
Content-Type: application/json 


###
# POST  http://localhost:8081/user/deleteAll